
rm -rf ./__pycache__
rm -rf ./tests/__pycache__
rm -rf ./spores/__pycache__
rm -rf ./physics/__pycache__
rm -rf ./phases/__pycache__
rm -rf ./body/__pycache__
rm -rf ./rchetypes/__pycache__
rm -rf ./brain/__pycache__
rm -rf ./mechanics/__pycache__
rm -rf ./protocols/__pycache__
rm -rf ./drivers/__pycache__
rm -rf ./machine/__pycache__
rm -rf ./soul/__pycache__
rm -rf ./MagicMock
rm -rf ./tests/MagicMock
rm -rf ./tests/memories
rm -rf ./logs
rm -rf ./memories
rm -rf ./saves
rm -f ./lore/lenses.json
rm -f ./lore/akashic*
rm -f ./legacy.json
rm -rf ./output
rm -rf ./tests/tests_isolated_legacy_void.json
rm -rf ./tests_isolated_legacy_void.json
rm -rf ./tests/logs
rm -rf ./tests/saves
rm -rf ./tests/tests