"""
tests/test_macro.py
S.L.A.S.H. Integration Suite.
These tests do not mock internal engine routing. They boot the full Cathedral,
push data through the front door, and verify the physical reality of the output.
"""
import unittest
import os
import json
from unittest.mock import patch
from main import BoneAmanita
from presets import BoneConfig
from genesis import BoneGenesis
from struts import safe_set
from constants import Prisma


class MacroLifecycleTests(unittest.TestCase):
    def setUp(self):
        """Boot a fresh, fully integrated engine for every test."""
        self.config = {
            "boot_mode": "ADVENTURE",
            "config": BoneConfig,
            "mode_settings": {"village_suppression": []}
        }
        self.engine = BoneAmanita(self.config)
        self.test_save_dir = "tests/temp_saves"
        self.test_lore_dir = "tests/temp_lore"
        os.makedirs(self.test_save_dir, exist_ok=True)
        os.makedirs(self.test_lore_dir, exist_ok=True)
        if hasattr(self.engine, "akashic"):
            self.engine.akashic.save_dir = self.test_save_dir
            self.engine.akashic.data_dir = self.test_lore_dir
        if hasattr(self.engine, "chronos"):
            self.engine.chronos.SAVE_DIR = self.test_save_dir

    def tearDown(self):
        """Clean up the physical files generated by the tests."""
        for d in [self.test_save_dir, self.test_lore_dir]:
            if os.path.exists(d):
                for f in os.listdir(d):
                    os.remove(os.path.join(d, f))
                os.rmdir(d)

    def test_chronos_graceful_shutdown_and_hydration(self):
        """
        MEADOWS' TEST: Verifies Chronos can freeze the Village SimpleNamespace
        and accurately hydrate it upon reboot without throwing AttributeErrors.
        """
        self.engine.village.bureau.stamp_count = 99
        self.engine.health = 42.0
        save_msg = self.engine.chronos.save_checkpoint([])
        self.assertIn("quicksave.json", save_msg, "Chronos failed to write the save file.")
        self.engine.health = 100.0
        self.engine.village.bureau.stamp_count = 0
        success, _ = self.engine.chronos.resume_checkpoint()
        self.assertTrue(success, "Chronos failed to hydrate the quicksave.")
        self.assertEqual(self.engine.health, 42.0, "State variable (Health) failed to re-hydrate.")
        self.assertEqual(self.engine.village.bureau.stamp_count, 99, "Village SimpleNamespace failed to re-hydrate.")

    @patch('brain.akashic.TheAkashicRecord.save_to_disk')
    def test_akashic_glimmer_pipeline(self, mock_save):
        """
        THE SCHUR SHORTCUT: We bypass physical disk I/O entirely.
        We only verify that the EventBus successfully routed the Glimmer
        to the Akashic Record's save function with the correct geometry.
        """
        import uuid
        import time
        test_concept = f"EPIPHANY_{uuid.uuid4().hex[:6].upper()}"
        self.engine.events.publish("GLIMMER_FORMED", {
            "concept": test_concept,
            "paradigm": "A structural truth was found."
        })
        time.sleep(0.5)
        self.assertTrue(mock_save.called, "Akashic Record failed to intercept the GLIMMER_FORMED event.")
        args, _ = mock_save.call_args
        category = args[0]
        payload = args[1]
        self.assertEqual(category, "boons", "Event routed to the wrong save category.")
        self.assertTrue(any(test_concept in item for item in payload),
                        "The trigger word was missing from the Akashic payload.")

    def test_autophagy_structural_survival(self):
        """
        GORDON'S TEST: Verifies that when ATP is 0, the memory pruning math
        prioritizes eating recent, lightweight nodes over old, heavy load-bearing nodes.
        """
        mem_core = self.engine.embryo.mind.mem.memory_core
        mem_core.graph["LoadBearingWall"] = {"last_tick": 5, "edges": {"a": 10, "b": 10, "c": 10, "d": 20}}
        mem_core.graph["useless_typo"] = {"last_tick": 104, "edges": {}}
        target, _ = mem_core.cannibalize(current_tick=105)
        self.assertEqual(target, "useless_typo",
                         "FATAL: Autophagy ate the load-bearing wall instead of the useless recency node!")


if __name__ == "__main__":
    unittest.main()
