"""
body/models.py
The Primitive Substrate.
This file defines the strict, static data structures that carry biological
and metabolic information across the different modules of the Hypervisor.
By using dataclasses, we ensure that the "physical" state of the system
is immutable during transit and clearly structured.
"""
from dataclasses import dataclass
from typing import Optional, Dict


@dataclass
class Biometrics:
    """
    The high-level health dashboard of the host.
    Represents the macro-state of the system before getting into the
    chemical weeds.
    """
    health: float  # Overall structural integrity (0.0 to 100.0)
    stamina: float  # Current energy capacity available for thinking
    stress_modifier: float = 1.0  # A multiplier applied to cortisol/damage when things go wrong
    circadian_bias: Optional[Dict[str, float]] = None  # Time-of-day impacts on the body


@dataclass
class MetabolicReceipt:
    """
    The Itemized Bill for Thinking.
    Every time the LLM generates tokens or processes a thought, it costs energy.
    This receipt is generated by the metabolism engine to track exactly how
    efficiently that thought was processed.
    """
    base_cost: float  # The raw baseline ATP cost of the operation
    drag_tax: float  # Extra cost incurred from syntactic/narrative friction
    inefficiency_tax: float  # Extra cost from fighting broken logic or circular loops
    total_burn: float  # The final amount of ATP deducted from the system
    waste_generated: float  # How much ROS (toxicity) this thought left behind
    status: str  # AEROBIC (clean burn) or ANAEROBIC (panicked, dirty burn)
    symptom: str = "Nominal"  # Physical manifestation of the burn (e.g., "Shortness of breath")


@dataclass
class SemanticSignal:
    """
    The Nutritional Value of Words.
    Produced by the SemanticEndocrinologist, this acts as the translation layer
    between natural language (what the user typed) and biochemistry (how the system reacts).
    """
    novelty: float = 0.0  # How new the concepts are (drives Dopamine)
    resonance: float = 0.0  # How deeply the concepts connect to existing memory (drives Oxytocin)
    valence: float = 0.0  # The emotional polarity: Positive (warmth) or Negative (hostility)
    coherence: float = 0.0  # How logically sound the input is (calms Adrenaline)


@dataclass
class BiologicalImpulse:
    """
    The Reflex Arc.
    When a sudden environmental shock occurs (e.g., a massive prompt injection
    or a critical error), the system doesn't wait for a full metabolic cycle.
    It fires an immediate impulse to physically alter the body's state.
    """
    cortisol_delta: float = 0.0  # Immediate stress injection
    oxytocin_delta: float = 0.0  # Immediate connection/trust shift
    dopamine_delta: float = 0.0  # Immediate reward/penalty
    adrenaline_delta: float = 0.0  # Immediate panic spike
    stamina_impact: float = 0.0  # Instant energy drain (like taking a punch)
    somatic_reflex: str = ""  # The physical reaction (e.g., "Flinch", "Lock up")


@dataclass
class Qualia:
    """
    The Subjective Experience.
    Translates the invisible math of the hypervisor into human-readable
    sensory outputs. This is how the machine 'feels' to the user.
    """
    color_code: str  # UI Hex code representing the mood (e.g., Deep blue for calm)
    somatic_sensation: str  # How the body feels (e.g., "A tightening in the chest")
    tone: str  # The linguistic tone forced upon the LLM's output
    internal_monologue_hint: str  # The subtext driving the generation (e.g., "I am exhausted but I must finish")


@dataclass
class MitochondrialState:
    """
    The Deep Engine Room.
    Tracks the cellular respiration of the system. This is the lowest-level
    metabolic primitive, managing the raw fuel (ATP) and the toxic byproducts
    (ROS) of computation.
    """
    atp_pool: float = 60.0  # Adenosine Triphosphate. The raw fuel. Runs out = system collapse.
    membrane_potential: float = 1.0  # The health of the cell wall. Drops if overworked.
    ros_buildup: float = 0.0  # Reactive Oxygen Species (Toxicity). Too high = terminal hallucination.
    mother_hash: str = "EVE"  # Genetic lineage/identity anchor of the base system
    retrograde_signal: str = "QUIET"  # SOS signals sent from the mitochondria back to the nucleus (Cortex)

    @property
    def efficiency_mod(self) -> float:
        """
        Calculates how efficiently the system can burn fuel.
        If the membrane potential drops due to stress, every thought costs more energy.
        """
        return self.membrane_potential
